# Generated by Django 5.1.1 on 2024-09-13 09:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Examen', models.CharField(default='Examen', max_length=60, verbose_name='Nom Examen')),
                ('Date_Examen', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 12))),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_fonction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=50, verbose_name='Specialite')),
                ('module', models.CharField(max_length=200, verbose_name='Description')),
                ('prix_formation', models.IntegerField()),
                ('duree', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Module_Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Stagiaire', models.CharField(max_length=70)),
                ('Telephone', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Date_naissance', models.DateField()),
                ('Sexe', models.CharField(max_length=20)),
                ('Payement', models.IntegerField(verbose_name='Montant Paye')),
                ('photo', models.ImageField(upload_to='static/images/profile/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Etudiant', models.CharField(max_length=70)),
                ('Prenom_etudiant', models.CharField(max_length=70)),
                ('Telephone', models.IntegerField(default='656317630', unique=True)),
                ('Email', models.EmailField(max_length=70, unique=True)),
                ('Date_naissance', models.DateField()),
                ('Sexe', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='static/images/profile/', verbose_name='Photo')),
                ('adresse', models.CharField(max_length=60)),
                ('nom_parent', models.CharField(max_length=70)),
                ('tel_parent', models.IntegerField()),
                ('Specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.formation')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Inscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_inscript', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 12))),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.etudiant', verbose_name='Email Etudiant')),
                ('nom_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.formation', verbose_name='Formation Choisi')),
            ],
        ),
        migrations.CreateModel(
            name='Payement_Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_payement', models.CharField(max_length=50)),
                ('montant_paye', models.IntegerField()),
                ('Reste', models.IntegerField(default=100000)),
                ('Date_Payement', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 12))),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.etudiant', verbose_name='Montant Paye par ')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Personnel', models.CharField(max_length=70)),
                ('Prenom_Personnel', models.CharField(default='Teacher', max_length=64)),
                ('Telephone', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=70, unique=True)),
                ('addresse', models.CharField(default='Cameroun-Dchang', max_length=64, verbose_name='Adresse')),
                ('Date_naissance', models.DateField()),
                ('Sexe', models.CharField(default='Masculin', max_length=20)),
                ('Role', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='static/images/profile/', verbose_name='Photo')),
                ('Universite', models.CharField(default='NANFAH', max_length=64)),
                ('date_debut_universite', models.DateField(default=datetime.datetime(2024, 1, 16, 11, 12))),
                ('date_fin_universite', models.DateField(default=datetime.datetime(2024, 1, 16, 11, 12))),
                ('niveau_etude', models.CharField(default='Master', max_length=64)),
                ('pays', models.CharField(default='Cameroun', max_length=64)),
                ('Fonction', models.ManyToManyField(to='gestionpersonnel.fonction', verbose_name='Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Formation', models.ManyToManyField(to='gestionpersonnel.formation', verbose_name='Nom Formation')),
                ('Email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.personnel', verbose_name='Email Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_Etudiant', models.IntegerField()),
                ('Date_Resultat', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 12))),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.etudiant', verbose_name='Nom Etudiant')),
                ('Nom_Examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.examen', verbose_name='Nom Examen')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription_Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_inscription', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 12))),
                ('Nom_Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.personnel', verbose_name='Nom_Personnel')),
                ('Nom_Stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.stagiaire', verbose_name='Nom_stagiare')),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionpersonnel.personnel', verbose_name='Email Enseignant')),
                ('Nom_Formation', models.ManyToManyField(to='gestionpersonnel.formation', verbose_name='Nom Formation')),
            ],
        ),
    ]
